[project]
name = "AutoML-pycaret"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "numpy>=2.1.3",
    "pandas>=2.2.3",
    "ydata-profiling>=4.16.1",
]
